apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-container
        image: gcr.io/lbg-uplift-project/dwr-api-app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080